### ISSUE TITLE
Syncthing doesn're remember GUI name and password

### ISSUE THREAD

**Issue by psmith1303** [kastelo/syncthing-synology#1]
I've done a fresh install of Syncthing, and I get the usual message that:

> The Syncthing admin interface is configured to allow remote access without a password.

So, I set an name and password and save it ... but it doesn't stay saved. Each time I go to synthing it warns me again, and when I check there is no user and password set

**Comment by psmith1303** [comment]
Here are the perms:
```

drwxrwxrwx+  4 syncthing.net syncthing.net  4096 Mar 16 09:39 .
drwxr-xr-x  15 root          root           4096 Mar 16 09:18 ..
-rwxrwxrwx+  1 syncthing.net syncthing.net   615 Mar 16 09:19 cert.pem
-rwxrwxrwx+  1 syncthing.net syncthing.net  6085 Mar 16 09:25 config.xml
-rwxrwxrwx+  1 syncthing.net syncthing.net    66 Mar 16 09:28 csrftokens.txt
drwxrwxrwx+  3 root          root           4096 Mar 16 09:18 @eaDir
-rwxrwxrwx+  1 syncthing.net syncthing.net   603 Mar 16 09:19 https-cert.pem
-rwxrwxrwx+  1 syncthing.net syncthing.net   288 Mar 16 09:19 https-key.pem
drwxrwxrwx+  2 syncthing.net syncthing.net  4096 Mar 16 09:40 index-v0.14.0.db
-rwxrwxrwx+  1 syncthing.net syncthing.net   288 Mar 16 09:19 key.pem
-rwxrwxrwx+  1 syncthing.net syncthing.net 17675 Mar 16 09:40 syncthing.log

```

**Comment by psmith1303** [comment]
Hmmm, I don't seem to be to save anything in settings ... but I can add folders and devices (so the config file is being written to).

**Comment by calmh** [comment]
I can't reproduce your problem, and I have no idea how it could happen.

**Comment by psmith1303** [comment]
Okay.
I've tried uninstalling and reinstalling. Now it won't even start. I wonder what I've done wrong.

**Comment by psmith1303** [comment]
I'm not sure why, but everything is okay if I use http. If I uses https I get this problem.

I guess https is not meant to work, so let's close this

**Comment by calmh** [comment]
I can’t imagine the connection, and https is certainly intended to work. :) Honestly this feels like some sort of browser issue.
