### ISSUE TITLE
DS "Failed to install "Syncthing". This package is not published by Synology Inc."

### ISSUE THREAD

**Issue by SongLifter** [kastelo/syncthing-synology#10]
I'm using Synology DSM 6.2.3-25426 Update 2 on a DS 1819+

I added the SyncThing Package under Community successfully as documented [here](https://docs.kastelo.net/synology/installing/), but when I click "Install", I get the following error: "Failed to install "Syncthing". This package is not published by Synology Inc."

I don't see that I'm doing anything wrong here.

**Comment by fstaffa** [comment]
Had the same issue, following fixed it: 

"Log into your NAS as administrator and go to Main Menu → Package Center → Settings and set Trust Level to Synology Inc. and trusted publishers."
