### ISSUE TITLE
Filesystem Watcher Errors for SynologyDrive folder 

### ISSUE THREAD

**Issue by rickdgit** [kastelo/syncthing-synology#14]
Hi,

I'd like to use SyncThing to sync Synology Drive folder(I know this may not be a good idea).

I've followed the https://docs.kastelo.net/synology/sharing/ to config the permission. 
"Ignore Permissions" checked.
The sync fundtion is working but not the rescan.
I got the following:

`SynologyDrive | error while traversing /volume1/homes/user/Drive/SynologyDrive: permission denied`

I wonder do I need specific handles for SynologyDrive folder ?

Thanks

**Comment by rickdgit** [comment]
I also sync another folder under ~/Drive folder(i.e. ~/Drive/photo) - I do not see any permission issues at all
I compared the permission of ~/Drive/SynologyDrive and  ~/Drive folder. They look the same.
Also, Im not sure the config & log location for the synology package. I can dig more if you can share the log location.

Please let me know if you have any other suggestions

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support. There's already a lot of topics about synology permission problems. And generally the forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
