### ISSUE TITLE
Listening on port 80/443 by default if WebStation is enabled: dangerous

### ISSUE THREAD

**Issue by slokhorst** [kastelo/syncthing-synology#16]
I just installed this package on my Synology box and was surprised to find it accessible at https://mysyno.example.com/syncthing/, which is publicly accessible in my case. This contradicts [the docs](https://docs.kastelo.net/synology/installing/) which say:
> Syncthing will by default be available on port 8384 without authentication. 

So by default it is also available on port 80 and 443! (only when WebStation is running I guess?)

This seems to be caused by `/etc/nginx/conf.d/www.syncthing.conf` which proxies `/syncthing/` to `http://127.0.0.1:8384/`.

I would suggest not placing this file by default, or at least strongly warning users of this (just like you do for port 8384).

**Comment by calmh** [comment]
Closing as we're no longer providing updates for this package and this repo is archived.
