### ISSUE TITLE
Syncthing package does not appear in package center

### ISSUE THREAD

**Issue by richard-fagot** [kastelo/syncthing-synology#17]
DS213+ 
DSM 6.2.4-25556 

After adding the https://synology.kastelo.net/ and refreshing the community list, Syncthing does not appear.

Is it incompatible with my Synology ?

**Comment by carballada** [comment]
it's the same on my case

DS119j
DSM 6.2.4-25556

**Comment by bradyb109** [comment]
Same here.

DS212j
DSM 6.2.4-25556

**Comment by calmh** [comment]
I'm not sure what you are suffering from unfortunately; this works much the same as it always has on my Synologies. :/

**Comment by calmh** [comment]
Closing as we're no longer providing updates for this package and this repo is archived.
