### ISSUE TITLE
'Invalid file format' when installing via package center

### ISSUE THREAD

**Issue by dominikkaminski** [kastelo/syncthing-synology#18]
Helllo,
first of all thanks for providing this Synology package.

I want to install it on my DS718+ but after hitting the Install button, the message `Snycthing: Invalid file format. Please contact the package developer`occurs.

System: 
Model name: DS718+
CPU: Intel Celeron J3455
CPU Clockrate: 1.5 GHz
CPU Cores: 4
RAM: 2 GB
DSM: DSM 7.0-41890

![image](https://user-images.githubusercontent.com/27898950/134909145-58b2c26c-4aa2-4992-9758-c56aca4a3c35.png)

Thanks in advance!

**Comment by arcuru** [comment]
+1

I also ran into this issue using a DS220+

EDIT: I am running DSM 7 which isn't supported (See #12, which I missed before posting). This may just be the new error message when trying to run on DSM 7.

**Comment by lum7671** [comment]
Model name: DS720+ and DS216j
also...

**Comment by loeffelsteve** [comment]
Got the same issue on DS216 running DSM 7.0.1-42218

**Comment by acolomb** [comment]
What is the name of the file you tried to install?  Does it end in `.spk`?

Or did you actually add the package source as explained in the docs?

**Comment by loeffelsteve** [comment]
Hi Andre,
It doesnt tell, see below. I just pressed the install button.
![InvalidFileformat](https://user-images.githubusercontent.com/94600307/142753505-862d0a6c-ebff-4e5e-8434-7aac58869cae.jpg)

Cheers
Kai

**Comment by timcappalli** [comment]
Same here.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/6476604/144116207-6c81e515-68c4-456c-83b8-cb82783f6a0e.png">

Synology DS1515+ running DSM 7.0-41890

**Comment by arcuru** [comment]
I'll repeat my message above, this is just the error message on DSM 7, which is not supported by this package (See #12)

Use the Syncthing package from [SynoCommunity](https://synocommunity.com/), which supports DSM 7.

**Comment by loeffelsteve** [comment]
Many thank, i got that package from SynoCommunity running.

**Comment by calmh** [comment]
Closing as we're no longer providing updates for this package and this repo is archived.
