### ISSUE TITLE
Broken documentation link in the readme

### ISSUE THREAD

**Issue by mikl** [kastelo/syncthing-synology#19]
[README.md](https://github.com/kastelo/syncthing-synology/blob/main/README.md) currently states:

> There is documentation available at https://docs.kastelo.net/synology/.

However, following that link brings you to this very empty page with no documentation to be found:

<img width="1167" alt="Screenshot 2021-10-29 at 02 38 08" src="https://user-images.githubusercontent.com/10263/139354594-a0b64e8e-e872-42aa-a226-126f00bb5de9.png">

**Comment by calmh** [comment]
Yeah that's not great

**Comment by calmh** [comment]
Fixed, thanks for noticing and letting us know!
