### ISSUE TITLE
No local filesystem permissions

### ISSUE THREAD

**Issue by sophistifunk** [kastelo/syncthing-synology#2]
It seems the Syncthing service can't actually write to the drive?

<img width="859" alt="image" src="https://user-images.githubusercontent.com/142591/79285146-09d67a80-7f00-11ea-9d49-49b5455217bb.png">

Any ideas?

**Comment by calmh** [comment]
You need to grant permissions: https://docs.kastelo.net/synology/sharing/

**Comment by sophistifunk** [comment]
That didn't seem to be any help, I'm not trying to share stuff *from* my Synology, just add it to the safe-havens for existing folders. It seems to be working now once I changed the default folder path in Syncthing settings from `~/` to `~/syncthing-data/`.

Please consider adding this configuration change to the installation procedure if possible, or at least adding it to the "installation" page in big letters if Synology's package management somehow precludes it. Unless what I've done is going to fuck something up, in which case please let me know :D

**Comment by kakra** [comment]
The easiest way is probably to create a shared folder "syncthing", add "syncthing.net" user with read/write permissions and set it as a default folder for new shares. That way, you can also access all sync folders from the Synology web UI.

**Comment by calmh** [comment]
Closing as we're no longer providing updates for this package and this repo is archived.
