### ISSUE TITLE
cant install syncthing on a DS213+

### ISSUE THREAD

**Issue by joulester** [kastelo/syncthing-synology#4]
Hello! I can´t find syncthing in the package center on my DS213+ or my DS214+. 
Is i not supported? 
can't find any info about it.

**Comment by calmh** [comment]
213+ is some PPC CPU that is not supported. I'm not sure what 214+ is, but if it doesn't present the package it's not one of the supported architectures, sorry.

**Comment by rvalle** [comment]
214+ is not showing, I can confirm.

**Comment by ghost** [comment]
Neither does it show up on a DS216j with DSM 6.2.3, but according to #6 it should be possible to fix this.
