### ISSUE TITLE
Multi-Arch builds

### ISSUE THREAD

**Issue by rvalle** [kastelo/syncthing-synology#6]
There seem to be no package for synology 214+, which I believe is arm/v7 arch.

@calmh have you looked into docker multi-arch builds?

With your setup I think it would be easy to achieve. Are your docker files pulling x86 code from third parties?

If not, I think the build would just work.

Do you have interest in a PR for AMR? would you be willing to publish the package?

If you are, I can help out.

**Comment by calmh** [comment]
We publish packages for armv7 and armv8. But the synology architecture family is complex and not all devices load the packages for their generic architecture. Perhaps because they differ in some way or are under-specced compared to the others in the same architecture. It's possible the DS214+ for some reason does not check for armv7 but only armadaaxp. We don't publish specific packages for single product families like that.

I'm not sure where Docker fits into this.

**Comment by calmh** [comment]
It could also be a problem with the (open source) package server not returning the right list for the 214+ depending on what precisely it asks for. I'm not sure how the api works exactly.

**Comment by rvalle** [comment]
I am not very familiar with Synology, we want out, in fact, and replace Cloudstation with Syncthing. We have this device in a remote office, and installing Synthing there is a good intermediate step.

I have been investigating other packages with similar issues... 

```
 So getting the package to install was easy:

    download the SPK
    unpack it
    change the architecture in the INFO file to armada370
    pack it up again
    install it manually
```

Apparently SPK is just  TAR. What is the URL of the ARM7 package? I cannot browse the repo... 

> I'm not sure where Docker fits into this.

we find it helpful for automated multi-arch builds. buildx + qemu-user-static in a gitlab pipeline. It is slow, but works.  are you building with virtual or physical targets?

**Comment by rvalle** [comment]
@calmh do you want me to test if that patch would work?
do you have the url of a ARM package?

**Comment by calmh** [comment]
I wouldn't be surprised if the package works even without patching. The raw package URLs are like

`https://synology.kastelo.net/download/syncthing.net-$arch-$version.spk`

so for example https://synology.kastelo.net/download/syncthing.net-armv7-1.7.1.spk

**Comment by rvalle** [comment]
here is what I did:

I downloaded your the package, uploaded to my synology and tested a manual install with the spk as it is: rejects the package for not been suitable for this device.

as expected, the spk is just a tar file. I did modify the INFO file with:

```
arch="alpine alpine4k armadaxp"
```
then I attempted the same manual installation and.... it WORKS!

![Screenshot from 2020-08-07 09-39-12](https://user-images.githubusercontent.com/412837/89621942-823bbf80-d892-11ea-80bb-7a6aeb6af1ec.png)

I can reach the admin web and managed to create 2 shares and sync 3GBs... it all looks just fine.

I guess we would need to patch SPKs as a last step in the bild process with a know-to-work list or architectures or something. I guess there are other Synology models that work with the packages you are creating.

Do you have a CI system or something for this repo?

**Comment by PaulLebmann** [comment]
I can confirm that the method @rvalle described works also for the DS215j when adding the "armada375" tag in the syncthing 1.8.0 armv7 package.

The admin Interface is working and after I changed the base download directory to a directory with write access for the "syncthing" group I was able to start sharing folders. At the moment the initial sync is still running, but it seems to work fine.

**Comment by ghost** [comment]
I hacked together something to solve this: #7.
Let me know what you think about it!

**Comment by calmh** [comment]
In theory the new 1.8.0.1 package should be installable on these armada boxes then, and also geminilake.

**Comment by ghost** [comment]
> In theory the new 1.8.0.1 package should be installable on these armada boxes then, and also geminilake.

Awesome! I just installed 1.8.0.1 from the Kastelo repository on my DS216j with armada385 and it seems to work just fine.
Thanks for the fast merge and deploy!
