### ISSUE TITLE
DS418 - SyncThing is outdated

### ISSUE THREAD

**Issue by kakra** [kastelo/syncthing-synology#9]
The package manager shows 1.3.4.1 as the current version which seems pretty old to me.

![image](https://user-images.githubusercontent.com/17684/97790042-b4289d80-1bc5-11eb-9787-86480239c80e.png)

**Comment by acolomb** [comment]
~~According to the [repository page](https://synocommunity.com/package/syncthing), the rtd1296 architecture should be on v1.7.1-20 by now.  Don't be fooled by that version though, as the Syncthing binary keeps itself up-to-date independently of SPK upgrades.  So you might in fact already have the most recent version running, just not the latest SPK version.~~

~~If no upgrade to v1.7.1 show in Package Manager, are you sure that the community package source is correctly added?~~

Scratch that, wrong repository I was talking about here. Sorry!

**Comment by kakra** [comment]
Actually, I just switched from the alternative community version (SynoCommunity) to the Kastelo one because the other version no longer booted. Took me some time to figure out how to migrate my configuration over because it's stored in a different location but all my folders and pairings are back again and working, and SyncThink is currently syncing status with my other devices.

I added the Kastelo Inc. repo as documented.

SyncThing itself reports it's running 1.3.4:

![image](https://user-images.githubusercontent.com/17684/97790226-19c95980-1bc7-11eb-9240-d65855049ec5.png)

**Comment by acolomb** [comment]
> SyncThing itself reports it's running 1.3.4:

That's to be expected, as this package here disables the internal updater and relies on SPK updates instead.

Seems like your architecture is not properly picked up from the generated package architectures.

**Comment by kakra** [comment]
> Seems like your architecture is not properly picked up from the generated package architectures.

Yeah, that's why I'm here. Looking at some of the closed issue, it looks like some architecture override may be missing.

**Comment by acolomb** [comment]
This is not the first report where the SynoCommunity package stopped working recently by the way.  I'm clueless as to why though, since my two Synologys run it just fine even right now.

**Comment by kakra** [comment]
Interesting... For me, it said "starting", then some seconds later it said "stopped". I checked the logs and found no clues. Then I found that a new "official" (?) package was available, same name but official repos and I thought: Okay, maybe this is officially supported now, and thus the other no longer works.

At least, I now know how to transfer the database between both packages so I could easily go back to the other.

**Comment by acolomb** [comment]
> Interesting... For me, it said "starting", then some seconds later it said "stopped".

That's https://github.com/SynoCommunity/spksrc/issues/4212.  Good that you found this package instead to have some working solution.  Hope your outdated version will be resolved soon (though I can't help with that).

**Comment by kakra** [comment]
The package is still pinned at this old version...

**Comment by kakra** [comment]
Gone back to the package provided by @acolomb which seems to work again. Closing this as it looks like Kastelo has completely abandoned this package, it hasn't received updates in a long time.
